/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";

import modelPath from "./TV.glb";
import { useGLTF } from "@react-three/drei";

export default function TVModel(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(modelPath);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg.geometry}
        material={nodes.Leg.material}
        position={[-3.77, 0.99, 0]}
        rotation={[0, 1.24, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[0.04, 1.09, -0.04]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={nodes.Cylinder002.material}
            position={[-0.11, -0.05, 0.05]}
            scale={[0.31, 0.51, 0.31]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={nodes.Cylinder003.material}
            position={[-0.01, -0.05, 0.11]}
            scale={[0.31, 0.51, 0.31]}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_2.geometry}
        material={nodes.Leg_2.material}
        position={[3.79, 0.99, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={nodes.Cylinder006.material}
          position={[0.04, 1.09, -0.04]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={nodes.Cylinder004.material}
            position={[-0.01, -0.05, 0.11]}
            scale={[0.31, 0.51, 0.31]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005.geometry}
            material={nodes.Cylinder005.material}
            position={[-0.11, -0.05, 0.05]}
            scale={[0.31, 0.51, 0.31]}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={nodes.Screen.material}
        position={[0, 5.52, 0.24]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(modelPath);
